name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up 
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Build mvn
        working-directory: webtest-master
        run: mvn clean package -DskipTests

      - name: Run all 8 tests
        working-directory: webtest-master
        run: mvn test
