name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test
